In [1]:
from Utils.MidiParseHandler import *
from pathlib import Path
import glob
import os
import music21 as m21

In [2]:
import numpy as np
import copy
import itertools
import collections
from pretty_midi import PrettyMIDI, Note, Instrument


In [3]:
from Utils.NotesSeq import * 
from Utils.EventSeq import *
from Utils.ControlSeq import *

In [6]:
import dataset
import torch

In [6]:
midi_files = glob.glob(os.path.join('Dataset-RAW', '*.mid'))

In [13]:
data_files = glob.glob(os.path.join('Processed-RAW','*'))

In [15]:
data_files[1]

'Processed-RAW/Canon_4_mains_piano.mid-b506cfe2666c100299a0ae2891ea9a7a.data'

In [20]:
eventseq, es2, controlseq, cs2 = torch.load(data_files[0])

In [22]:
print(cs2)

[[ 7 31 21 ... 74  0 21]
 [ 7 31 21 ... 74  0 21]
 [ 7 33 22 ... 66  0 22]
 ...
 [ 0 21 21 ... 21 21 21]
 [ 0 21 21 ... 21 21 21]
 [ 0 21 21 ... 21 21 21]]


In [7]:
tr1, tr2 = NoteSeq.from_midi_file(midi_files[1])

 4 tracce : Dataset-RAW/Tema_del_Bolero_de_Ravel_-_PIANO_FCIL.mid


/Users/mattiacarolo/.pyenv/versions/3.9.6/envs/Music/lib/python3.9/site-packages/pretty_midi/pretty_midi.py:100: RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks.  This is not a valid type 0 or type 1 MIDI file.  Tempo, Key or Time Signature may be wrong.
  warnings.warn(


In [8]:
tr1.notes

[Note(start=0.000000, end=1.361743, pitch=72, velocity=80),
 Note(start=0.000000, end=0.452652, pitch=48, velocity=80),
 Note(start=0.454545, end=0.907197, pitch=55, velocity=80),
 Note(start=0.909091, end=1.361743, pitch=48, velocity=80),
 Note(start=1.363636, end=1.589015, pitch=71, velocity=80),
 Note(start=1.363636, end=1.816288, pitch=55, velocity=80),
 Note(start=1.590909, end=1.816288, pitch=72, velocity=80),
 Note(start=1.818182, end=2.043561, pitch=74, velocity=80),
 Note(start=1.818182, end=2.270834, pitch=43, velocity=80),
 Note(start=2.045455, end=2.270834, pitch=72, velocity=80),
 Note(start=2.272727, end=2.498106, pitch=71, velocity=80),
 Note(start=2.272727, end=2.725379, pitch=55, velocity=80),
 Note(start=2.500000, end=2.725379, pitch=69, velocity=80),
 Note(start=2.727273, end=3.179925, pitch=72, velocity=80),
 Note(start=2.727273, end=3.179925, pitch=48, velocity=80),
 Note(start=3.181818, end=3.407197, pitch=72, velocity=80),
 Note(start=3.181818, end=3.634470, pitc

In [5]:
midi = PrettyMIDI(midi_files[0])

/Users/mattiacarolo/.pyenv/versions/3.9.6/envs/Music/lib/python3.9/site-packages/pretty_midi/pretty_midi.py:100: RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks.  This is not a valid type 0 or type 1 MIDI file.  Tempo, Key or Time Signature may be wrong.
  warnings.warn(


In [13]:
programs = range(128)

print(len(midi.instruments))

notes = itertools.chain(*[
            inst.notes for inst in midi.instruments
            if inst.program in programs and not inst.is_drum])

4


In [ ]:
from itertools import chain

# Specify the indices of the wanted tracks for each group
group1_indices = [0, 1, 2]  # Example indices for the first group
group2_indices = [3, 4, 5]  # Example indices for the second group

# Filter notes for the first group of tracks
group1_notes = chain(*[
    midi.instruments[i].notes for i in group1_indices
])

# Filter notes for the second group of tracks
group2_notes = chain(*[
    midi.instruments[i].notes for i in group2_indices
])

# Now you have two separate iterables for each group of notes

In [12]:
notes

In [4]:
note_seq = NoteSeq.from_midi_file(midi_files[0])

/Users/mattiacarolo/.pyenv/versions/3.9.6/envs/Music/lib/python3.9/site-packages/pretty_midi/pretty_midi.py:100: RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks.  This is not a valid type 0 or type 1 MIDI file.  Tempo, Key or Time Signature may be wrong.
  warnings.warn(


In [8]:
print(note_seq)

TypeError: 'NoteSeq' object is not subscriptable